language: ruby
rvm:
  - 2.2.3

install:
  - npm install

script: gulp website:build

notifications:
  email:
    - julia.elman@gsa.gov
    - maya.ben-ari@gsa.gov
    - roger.ruiz@gsa.gov

branches:
  only:
    - 18f-pages
    - 18f-pages-staging
