label: Headers
order: 14
status: ready

# default template ("context") data
context:
  header:
    title: Department of Web Design

variants:
  - name: default
    label: Compare
    status: null

  - name: basic
    label: Basic header
    context:
      header:
        primary:
          search: true
          links:
            - text: Section one
              id: nav-section-one-basic
              links: &subnav_links
                - text: Page title one
                  href: 'javascript:void(0)'
                - text: Page title two
                  href: 'javascript:void(0)'
                - text: Page title three
                  href: 'javascript:void(0)'
            - text: Simple terms
              id: nav-section-two-basic
              links: *subnav_links
            - text: Distinct from each other
              href: 'javascript:void(0)'

  - name: basic-mega
    label: Basic with mega-menu
    context:
      header:
        primary:
          search: true
          links:
            - text: Section one
              id: nav-section-one-basic-mega
              links: *subnav_links
            - text: Simple terms
              id: nav-section-two-basic-mega
              links: *subnav_links
            - text: Distinct from each other
              href: 'javascript:void(0)'

  - name: extended
    label: Extended header
    context:
      header:
        primary:
          search: false
          links:
            - text: Section one
              id: nav-section-one-extended
              links: *subnav_links
            - text: Simple terms
              id: nav-section-two-extended
              links: *subnav_links
            - text: Distinct from each other
              href: 'javascript:void(0)'
        secondary:
          search: true
          links:
            - text: Secondary priority link
              href: '#'
            - text: Easy to comprehend
              href: '#'

  - name: extended-mega
    label: Extended with mega-menu
    context:
      header:
        primary:
          search: false
          links:
            - text: Section one
              id: nav-section-one-extended-mega
              links: *subnav_links
            - text: Simple terms
              id: nav-section-two-extended-mega
              links: *subnav_links
            - text: Distinct from each other
              href: 'javascript:void(0)'
        secondary:
          search: true
          links:
            - text: Secondary priority link
              href: '#'
            - text: Easy to comprehend
              href: '#'
