label: Headers

# default template ("context") data
context:
  header:
    title: U.S. Department of Web Design
    primary:
      search: true
      links:
        - text: Section one
          id: section-one
          links:
            - text: Sub-link one
              href: '#'
            - text: Sub-link two
              href: '#'
            - text: Sub-link three
              href: '#'
        - text: Simple terms
          id: section-two
          links:
            - text: Sub-link four
              href: '#'
            - text: Sub-link five
              href: '#'
            - text: Sub-link six
              href: '#'
        - text: Link one

variants:
  - name: default
    label: Demo
    context: {}

  - name: basic
    label: Basic header
    context: {}

  - name: basic-mega
    label: Basic with mega-menu
    context: {}

  - name: extended
    label: Extended header
    context:
      header: &extended_data
        primary:
          search: false
        secondary:
          search: true
          links:
            - text: Secondary priority link
              href: '#'
            - text: Easy to comprehend
              href: '#'

  - name: extended-mega
    label: Extended with mega-menu
    context:
      header: *extended_data

