label: Buttons
status: ready

variants:
  - name: primary
    context:
      category: primary
      label: Primary buttons
      classes: 'usa-button'

  - name: primary-alt
    context:
      category: primary
      label: Primary alt buttons
      classes: 'usa-button-primary-alt'

  - name: secondary
    context:
      category: secondary
      label: Secondary buttons
      classes: 'usa-button-secondary'

  - name: secondary-inverse
    context:
      category: secondary
      label: Secondary inverse buttons
      classes: 'usa-button-secondary-inverse'

  - name: gray
    context:
      category: secondary
      label: Gray buttons
      classes: 'usa-button-gray'

  - name: red
    context:
      category: secondary
      label: Red buttons
      classes: 'usa-button-red'

  - name: big
    context:
      category: 'big'
      label: Big button
      classes: 'usa-button-big'
